<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

  <!-- Параметры колесной базы -->
  <xacro:property name="wheel_separation" value="0.76"/>
  <xacro:property name="wheel_radius" value="0.17"/>

  <!-- Соединения колес -->
  <joint name="left_wheel_joint" type="continuous"/>
  <joint name="right_wheel_joint" type="continuous"/>
  <joint name="back_left_wheel_joint" type="continuous"/>
  <joint name="back_right_wheel_joint" type="continuous"/>

  <gazebo>
    <!-- Плагин дифференциального привода -->
    <plugin name="skid_steer_drive" filename="libgazebo_ros_diff_drive.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      
      <leftJoint>left_wheel_joint</leftJoint>
      <leftJoint>back_left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <rightJoint>back_right_wheel_joint</rightJoint>
      
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <torque>1000</torque>
      <updateRate>50.0</updateRate>
      <publishWheelTF>true</publishWheelTF>
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>
</robot>